name: Build Terracoin for x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   # lub windows/linux, ale to już mało istotne
    container:
      image: ubuntu:22.04
      options: --user root    # żeby mieć uprawnienia do apt-get i make

    steps:
      - uses: actions/checkout@v4

      - name: Clone Terracoin source
        run: |
          git clone --depth=1 https://github.com/terracoin/terracoin.git terracoin

      - name: Apply Terracoin Core patches
        run: |
          # 1) Boost placeholders patch for validationinterface.cpp
          sed -i '/validationinterface.h/a #include <boost\/bind\/bind.hpp>' terracoin/src/validationinterface.cpp
          sed -i '/#include <boost\/bind\/bind.hpp>/a using namespace boost::placeholders;' terracoin/src/validationinterface.cpp

          # 2) Include <deque> for httpserver.cpp
          sed -i '/boost\/foreach.hpp/a #include <deque>' terracoin/src/httpserver.cpp

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libtool \
            autoconf \
            automake \
            libboost-all-dev \
            libzmq3-dev \
            libdb++-dev \
            libssl-dev \
            libcurl4-openssl-dev

      - name: Configure & build
        run: |
          cd terracoin
          ./autogen.sh
          ./configure \
            CXXFLAGS="-DBOOST_BIND_GLOBAL_PLACEHOLDERS" \
            --without-gui \
            --enable-wallet \
            --with-zmq \
            --with-incompatible-bdb \
            --disable-tests \
            --disable-bench
          make -j$(nproc)

      - name: Upload terracoind binary
        uses: actions/upload-artifact@v4
        with:
          name: terracoind-x86_64
          path: terracoin/src/terracoind
