name: Build Terracoin for x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y \
          build-essential pkg-config libtool autoconf automake \
          libboost-all-dev libzmq3-dev libdb++-dev libssl-dev libcurl4-openssl-dev

      - name: Configure & build
        run: |
          ./autogen.sh
          ./configure \
            CXXFLAGS="-DBOOST_BIND_GLOBAL_PLACEHOLDERS" \
            --without-gui \
            --enable-wallet \
            --with-zmq \
            --with-incompatible-bdb \
            --disable-tests \
            --disable-bench
          make -j$(nproc)

      - name: Upload terracoind binary
        uses: actions/upload-artifact@v4
        with:
          name: terracoind-x86_64
          path: src/terracoind
