name: Build Terracoin for x86_64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git wget build-essential

      - name: Clone Terracoin source
        run: |
          git clone --depth=1 https://github.com/terracoin/terracoin.git terracoin

      - name: Apply Terracoin Core patches
        run: |
          # 1) Boost placeholders patch for validationinterface.cpp
          sed -i '/validationinterface.h/a #include <boost\/bind\/bind.hpp>' terracoin/src/validationinterface.cpp
          sed -i '/#include <boost\/bind\/bind.hpp>/a using namespace boost::placeholders;' terracoin/src/validationinterface.cpp
          # 2) Include <deque> for httpserver.cpp
          sed -i '/boost\/foreach.hpp/a #include <deque>' terracoin/src/httpserver.cpp

      - name: Install BerkeleyDB 4.8
        run: |
          cd /usr/local/src
          wget http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz
          tar xzf db-4.8.30.NC.tar.gz
          cd db-4.8.30.NC/build_unix
          ../dist/configure --prefix=/usr/local/BerkeleyDB.4.8 --enable-cxx --disable-shared --with-pic
          make -j$(nproc)
          make install
        # instalujemy BDB4.8 z myślą o wallet

      - name: Install other dependencies
        run: |
          apt-get update
          apt-get install -y \
            pkg-config \
            libtool \
            autoconf \
            automake \
            libboost-all-dev \
            libzmq3-dev \
            libssl-dev \
            libcurl4-openssl-dev

      - name: Configure & build
        env:
          BDB_PREFIX: /usr/local/BerkeleyDB.4.8
        run: |
          cd terracoin
          ./autogen.sh
          PKG_CONFIG_PATH="$BDB_PREFIX/lib/pkgconfig" \
          CXXFLAGS="-I$BDB_PREFIX/include -DBOOST_BIND_GLOBAL_PLACEHOLDERS" \
          LDFLAGS="-L$BDB_PREFIX/lib" \
          ./configure \
            --without-gui \
            --enable-wallet \
            --with-zmq \
            --with-incompatible-bdb \
            --disable-tests \
            --disable-bench
          make -j$(nproc)

      - name: Upload terracoind binary
        uses: actions/upload-artifact@v4
        with:
          name: terracoind-x86_64
          path: terracoin/src/terracoind

      - name: Upload Terracoin binaries
        uses: actions/upload-artifact@v4
        with:
          name: terracoin-binaries
          path: |
            terracoin/src/terracoind
            terracoin/src/terracoin-cli
